name: Daily Video Generator

on:
  schedule:
    # Roz shaam 7 baje (13:30 UTC) chalega
    - cron: '30 13 * * *'
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Code ko Checkout karna
        uses: actions/checkout@v3

      - name: Python 3.9 ko Setup karna
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: FFMPEG Install karna (MoviePy ke liye zaruri)
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # === YEH SABSE BADA AUR IMPORTANT CHANGE HAI ===
      # Humne installation aur execution ko ek hi step me jod diya hai
      - name: Dependencies Install karna aur Script Chalana
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Installation complete. Running the script now..."
          python create_video.py
