# Workflow ka naam, jo GitHub Actions tab me dikhega
name: Daily Video Generator (YouTube & Facebook)

on:
  # Yeh section batata hai ki workflow kab chalega
  schedule:
    # Yeh cron job hai. '30 13 * * *' ka matlab hai har din 13:30 UTC.
    # 7 PM IST (Indian Standard Time) = 13:30 UTC.
    - cron: '30 13 * * *'
  
  # Isse aap "Actions" tab me जाकर "Run workflow" button se manually bhi chala sakte hain
  workflow_dispatch:

jobs:
  # Ek hi job hai is workflow me, jiska naam 'build-and-upload' hai
  build-and-upload:
    # Yeh job Ubuntu (Linux) machine par chalega
    runs-on: ubuntu-latest

    steps: # Kaam karne ke steps
      # Step 1: Aapke code ko GitHub se runner machine par download karega
      - name: Code ko Checkout karna
        uses: actions/checkout@v4

      # Step 2: Python ko set up karega
      - name: Python 3.9 ko Setup karna
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: FFMPEG ko install karega, jo MoviePy ke liye zaruri hai
      - name: FFMPEG Install karna (MoviePy ke liye zaruri)
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # Step 4: Ek hi step me saari libraries install karega aur script chalayega
      - name: Dependencies Install karna, Verify karna aur Script Chalana
        env:
          # --- YouTube ke Secrets ---
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          # --- Facebook ke Secrets ---
          FACEBOOK_PAGE_ID: ${{ secrets.PAGE_ID }}
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
        run: |
          # Pehle zaruri libraries install karega
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          # Tasalli ke liye installed packages ki list dikhayega
          echo "---- Installation complete. Verifying installed packages... ----"
          pip list
          
          # Ab script chalayega
          echo "---- Verification complete. Running the script now... ----"
          python create_video.py
